-- Products become management-editable: description + auto-generated ids.
ALTER TABLE products ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('products', 'id'), (SELECT MAX(id) FROM products));

-- Multiple images per product, stored in S3 under products/ (public-read prefix).
CREATE TABLE product_images (
  id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  product_id SMALLINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  s3_key     TEXT NOT NULL UNIQUE,
  sort_order SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_product_images_product ON product_images (product_id, sort_order);

-- KYC document images, stored in S3 under kyc/{member_id}/ (private prefix,
-- served only via presigned GET). Review status stays on members.kyc_status.
CREATE TABLE kyc_documents (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  member_id     BIGINT NOT NULL REFERENCES members(id),
  doc_type      TEXT NOT NULL CHECK (doc_type IN ('pan', 'aadhaar', 'other')),
  s3_key        TEXT NOT NULL UNIQUE,
  original_name TEXT,
  uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_kyc_documents_member ON kyc_documents (member_id);
